name: watermark_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.2
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  awesome_watermark:
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
